services:
  libre311-db:
    networks:
      - unity-network
    container_name: libre311-db
    extends:
      file: app/docker-compose.deps.yml
      service: libre311-db

  libre311-api:
    container_name: libre311-api
    networks:
      - unity-network
    extends:
      file: app/docker-compose.api.yml
      service: libre311-api
    depends_on:
      libre311-db:
        condition: service_healthy
      local-mail-relay:
        condition: service_started
      libre311-imageserv:
        condition: service_started
    environment:
      SMTP_HOST: local-mail-relay
      SMTP_PORT: 1025
      SMTP_USERNAME: unity
      SMTP_PASSWORD: password

  local-mail-relay:
    container_name: local-mail-relay
    networks:
      - unity-network
    extends:
      file: app/docker-compose.deps.yml
      service: local-mail-relay

  libre311-imageserv:
    container_name: libre311-imageserv
    networks:
      - unity-network
    extends:
      file: app/docker-compose.deps.yml
      service: libre311-imageserv

  libre311-ui-dev:
    container_name: libre311-ui-dev
    networks:
      - unity-network
    build:
      dockerfile: DockerfileFrontend-dev
      context: .
    restart: no
    env_file:
      - frontend/.env.docker
    ports:
      - "3000:3000"
    depends_on:
      - libre311-api

  libre311-ui-prod:
    profiles:
      - prod
    container_name: libre311-ui-prod
    networks:
      - unity-network
    build:
      dockerfile: DockerfileFrontend-prod
      context: .
    restart: no
    env_file:
      - frontend/.env.docker
    ports:
      - "3000:80"
    depends_on:
      - libre311-api

networks:
  default:
    name: unity-network
    external: true
  unity-network:
    external: true
