# You must start docker-compose.local.yml prior to starting this
services:
  libre311-db:
    networks:
      - unity-network
    container_name: libre311-db
    extends:
      file: app/docker-compose.local-infra.yml
      service: libre311-db

  libre311-api:
    container_name: libre311-api
    networks:
      - unity-network
    extends:
      file: app/docker-compose.local-service.yml
      service: libre311-api
    depends_on:
      libre311-db:
        condition: service_healthy

  libre311-ui:
    container_name: libre311-ui
    networks:
      - unity-network
    build:
      dockerfile: FrontendDockerfile
      context: .
    restart: unless-stopped
    environment:
      VITE_BACKEND_URL: http://localhost:8080/api
    env_file:
      - frontend/.env
    ports:
      - "3000:80"

networks:
  default:
    name: unity-network
    external: true
  unity-network:
    external: true
