CREATE TABLE IF NOT EXISTS projects (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    boundary POLYGON NOT NULL SRID 4326,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    jurisdiction_id VARCHAR(255) NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (jurisdiction_id) REFERENCES jurisdictions(id) ON DELETE CASCADE
);

ALTER TABLE service_requests
ADD COLUMN project_id BIGINT,
ADD CONSTRAINT FK_SERVICE_REQUESTS_PROJECT
FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL;
