package app.security;

public enum Permission {
    AUTH_SERVICE_EDIT_SYSTEM("AUTH_SERVICE_EDIT-SYSTEM"),
    AUTH_SERVICE_VIEW_SYSTEM("AUTH_SERVICE_VIEW-SYSTEM"),
    AUTH_SERVICE_EDIT_TENANT("AUTH_SERVICE_EDIT-TENANT"),
    AUTH_SERVICE_VIEW_TENANT("AUTH_SERVICE_VIEW-TENANT"),
    LIBRE311_ADMIN_EDIT_SYSTEM("LIBRE311_ADMIN_EDIT-SYSTEM"),
    LIBRE311_ADMIN_VIEW_SYSTEM("LIBRE311_ADMIN_VIEW-SYSTEM"),
    LIBRE311_ADMIN_EDIT_TENANT("LIBRE311_ADMIN_EDIT-TENANT"),
    LIBRE311_ADMIN_VIEW_TENANT("LIBRE311_ADMIN_VIEW-TENANT"),
    LIBRE311_ADMIN_EDIT_SUBTENANT("LIBRE311_ADMIN_EDIT-SUBTENANT"),
    LIBRE311_ADMIN_VIEW_SUBTENANT("LIBRE311_ADMIN_VIEW-SUBTENANT"),
    LIBRE311_REQUEST_EDIT_SYSTEM("LIBRE311_REQUEST_EDIT-SYSTEM"),
    LIBRE311_REQUEST_VIEW_SYSTEM("LIBRE311_REQUEST_VIEW-SYSTEM"),
    LIBRE311_REQUEST_EDIT_TENANT("LIBRE311_REQUEST_EDIT-TENANT"),
    LIBRE311_REQUEST_VIEW_TENANT("LIBRE311_REQUEST_VIEW-TENANT"),
    LIBRE311_REQUEST_EDIT_SUBTENANT("LIBRE311_REQUEST_EDIT-SUBTENANT"),
    LIBRE311_REQUEST_VIEW_SUBTENANT("LIBRE311_REQUEST_VIEW-SUBTENANT");

    private final String permission;

    Permission(String permission) {
        this.permission = permission;
    }

    public String getPermission() {
        return permission;
    }
}
