gcp:
  project-id: ${GCP_PROJECT_ID}

micronaut:
  application:
    name: Libre311
  object-storage:
    gcp:
      default:
        bucket: ${STORAGE_BUCKET_ID:`your-client-id-here.apps.googleusercontent.com`}
  http:
    services:
      auth:
        urls:
          - "http://localhost:8080"
  security:
    token:
      jwt:
        signatures:
          jwks:
            unityauth:
              url: ${UNITY_AUTH_JWKS_ENDPOINT} #alternatively we can supply the base and append '.well-known/jwks.json' if that convention is followed
    intercept-url-map:
      - pattern: /info
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  data:
    pageable:
      size-parameter-name: page_size
datasources:
  default:
    db-type: ${LIBRE311_DB_TYPE}
test-resources:
  containers:
    mysql:
      image-name: mysql:8.2
jpa:
  default:
    entity-scan:
      packages: "app.model"
    properties:
      hibernate:
        hbm2ddl:
          auto: ${LIBRE311_AUTO_SCHEMA_GEN:update}
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        type: trace
netty:
  default:
    allocator:
      max-order: 3
app:
  discovery:
    changeset: ${LIBRE311_DISCOVERY_CHANGESET_DATETIME:`2012-09-14T08:00:00-07:00`}
    contact: ${LIBRE311_DISCOVERY_CONTACT_MESSAGE:`Contact admin@test.test for assistance`}
    key-service: "Visit [endpoint here] to request an API Key"
    endpoints:
      - specification: "http://wiki.open311.org/GeoReport_v2"
        url: ${LIBRE311_DISCOVERY_PRODUCTION_URL:`http://localhost:8080/api`}
        changeset: ${LIBRE311_DISCOVERY_CHANGESET_DATETIME:`2012-09-14T08:00:00-07:00`}
        type: "production"
        formats:
          - "text/xml"
          - "application/json"
      - specification: "http://wiki.open311.org/GeoReport_v2"
        url: ${LIBRE311_DISCOVERY_TEST_URL:`http://localhost:8080/api`}
        changeset: ${LIBRE311_DISCOVERY_CHANGESET_DATETIME:`2012-09-14T08:00:00-07:00`}
        type: "test"
        formats:
          - "text/xml"
          - "application/json"
  image-storage:
    bucket-url-format: "https://storage.googleapis.com/%s/"
    bucket:  ${STORAGE_BUCKET_ID:`your-client-id-here.apps.googleusercontent.com`}
    append-object-url-format: "%s"
  recaptcha:
    secret: ${RECAPTCHA_SECRET:`recaptchaSecret`}
  safesearch:
    key: ${SAFESEARCH_KEY:`safesearchKey`}