services:
  libre311-db:
    container_name: libre311-db
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - unity-network
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: libre311
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
    ports:
      - "23306:3306"

networks:
  default:
    name: unity-network
    external: true
  unity-network:
    external: true
