package app;

import app.model.service.Service;
import app.model.service.ServiceRepository;
import app.model.service.ServiceType;
import app.model.servicerequest.ServiceRequest;
import app.model.servicerequest.ServiceRequestRepository;
import app.model.servicerequest.ServiceRequestStatus;
import io.micronaut.context.annotation.ConfigurationProperties;
import io.micronaut.context.annotation.Requires;
import io.micronaut.core.convert.format.MapFormat;
import io.micronaut.core.util.StringUtils;
import io.micronaut.runtime.event.annotation.EventListener;
import io.micronaut.runtime.server.event.ServerStartupEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.Map;

@Requires(property = "wemove.bootstrap.data.enabled", value = StringUtils.TRUE)
@ConfigurationProperties("wemove.bootstrap")
public class Bootstrap {

    @MapFormat(transformation = MapFormat.MapTransformation.NESTED)
    private Map<String, Object> data;

    private final ServiceRepository serviceRepository;
    private final ServiceRequestRepository serviceRequestRepository;
    private static final Logger LOG = LoggerFactory.getLogger(Bootstrap.class);

    public Bootstrap(ServiceRepository serviceRepository, ServiceRequestRepository serviceRequestRepository) {
        this.serviceRepository = serviceRepository;
        this.serviceRequestRepository = serviceRequestRepository;
    }

    @EventListener
    public void devData(ServerStartupEvent event) {
        if(data != null) {

            if(data.containsKey("services")) {
                ((List<Map<String, ?>>) data.get("services")).stream().forEach(svc -> {
                    String serviceName = (String) svc.get("serviceName");
                    Service service = new Service(serviceName);
                    service.setServiceCode((String) svc.get("serviceCode"));
                    service.setDescription((String) svc.get("description"));
                    service.setMetadata((boolean) svc.get("metadata"));
                    service.setType(ServiceType.valueOf(((String) svc.get("type")).toUpperCase()));

                    serviceRepository.save(service);
                });
            }

            if(data.containsKey("service-requests")) {
                ((List<Map<String, ?>>) data.get("service-requests")).stream().forEach(svcReq -> {
                    ServiceRequest serviceRequest = new ServiceRequest();
                    serviceRequest.setDescription((String) svcReq.get("description"));
                    serviceRequest.setAddressString((String) svcReq.get("address"));
                    serviceRequest.setLatitude((String) svcReq.get("lat"));
                    serviceRequest.setLongitude((String) svcReq.get("long"));
//                    serviceRequest.setId((String) svcReq.get("service_request_id")); // auto-generated by db
                    serviceRequest.setServiceCode((String) svcReq.get("service_code"));
                    serviceRequest.setStatus(ServiceRequestStatus.valueOf(((String) svcReq.get("status")).toUpperCase()));
                    serviceRequest.setZipCode((String) svcReq.get("zipcode"));
                    serviceRequest.setAgencyResponsible((String) svcReq.get("agency_responsible"));
                    serviceRequest.setAgencyResponsible((String) svcReq.get("agency_responsible"));
                    serviceRequest.setMediaUrl((String) svcReq.get("media_url"));
                    serviceRequest.setAddressId((String) svcReq.get("address_id"));
                    serviceRequest.setServiceNotice((String) svcReq.get("service_notice"));
                    serviceRequest.setStatusNotes((String) svcReq.get("status_notes"));

                    serviceRequestRepository.save(serviceRequest);
                });
            }
        }
    }

    public void setData(Map<String, Object> data) {
        this.data = data;
    }
}
