# Copyright 2023 Libre311 Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run the server with Gradle
      env:
        VITE_BACKEND_URL: /api
        MICRONAUT_ENVIRONMENTS: dev,dev-data
      run: |
        ./gradlew app:run &
    - name: Create and populate .env file
      working-directory: ./frontend
      env:
        VITE_BACKEND_URL: /api
        VITE_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        VITE_GOOGLE_RECAPTCHA_KEY: ${{ secrets.GOOGLE_RECAPTCHA_KEY }}
      run: |
          touch .env
          echo VITE_BACKEND_URL="$VITE_BACKEND_URL" >> .env
          echo VITE_GOOGLE_API_KEY="$VITE_GOOGLE_API_KEY" >> .env
          echo VITE_GOOGLE_RECAPTCHA_KEY="$VITE_GOOGLE_RECAPTCHA_KEY" >> .env

          echo "cat .env"
          cat .env
      shell: bash
    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./frontend
    - name: Run Playwright tests
      run: npx playwright test --workers=2
      working-directory: ./frontend
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
